// Code generated by go run ./scripts/generate-runtime-lock.go; DO NOT EDIT.

package runtimeidentity

const (
	GVisorRelease                = "release-20260907.0"
	GVisorCommit                 = "7c6199801fd233d6d55309af4645d4746a077de7"
	GVisorSourceRepository       = "https://github.com/google/gvisor.git"
	GVisorPatchPath              = "tools/gvisor/release-20260907.0.patch"
	GVisorPatchSHA256            = "4e932cede0d3d1c8596346b06191c2aaed2f8974289d690ade1594948b7674f3"
	GVisorBazelModuleLockSHA256  = "8402c7beb4baf2c666f4b78e400ea3f15514b56117598c2cb5411d6a35208d34"
	GVisorBuilderImageRepository = "us-central1-docker.pkg.dev/gvisor-presubmit/gvisor-presubmit-images/default_x86_64"
	GVisorBuilderImageTag        = "c48008cead6d6826"
	GVisorBuilderImageDigest     = "sha256:9afba722516843795c026fbe3b7cd8a8f6b729d241e656a70af1ad46fe09406c"
	GVisorBuilderArchitecture    = "amd64"
	BazelVersion                 = "8.3.1"
	BazelLinuxX8664SHA512        = "c876a1619c885f44f3bdc87998eca59c79581954631c9d7fab4eb53cc0409b68e4be74c08ef3fe599c51b75d56262070f0c314f9908336221e7764fdf981b7f5"
	DockerMinimumEngine          = "29.8.1"
	DockerCIEngine               = "29.8.1"
	DockerCEPackage              = "5:29.8.1-1~ubuntu.24.04~noble"
	DockerCECLIPackage           = "5:29.8.1-1~ubuntu.24.04~noble"
	ContainerdPackage            = "2.3.5-1~ubuntu.24.04~noble"
	NodeImageReference           = "node:24.21.0-slim@sha256:713cfbf4a0ac19f40e1bb9919893e126b74a5c8cf5d0623c9f89515c8f74c6fa"
	NodeNPMVersion               = "11.19.0"
	PythonImageReference         = "python:3.14.7-slim-bookworm@sha256:23c59390fc717bf09f9336908199a0ae75d9c4264bf296123f94ad772fea3b52"
	PythonVersion                = "3.14.7"
	PipVersion                   = "26.2.1"
	GoImageReference             = "golang:1.26.8-bookworm@sha256:abe4f87f354c4f6d7ee3fb11b241c6b6c24a32ca50a2ebcc30493a2168e14048"
	GoVersion                    = "1.26.8"
	GoArchitecture               = "amd64"
	RustImageReference           = "rust:1.99.0-bookworm@sha256:59037199c44290f2befcdd58dcc540164763fc296950255aaefeef096a1866b0"
	RustVersion                  = "1.99.0"
	RustArchitecture             = "amd64"
	RustTarget                   = "x86_64-unknown-linux-gnu"
	PythonInterpreterTag         = "cp314"
	PythonABITag                 = "cp314"
	PythonPlatformTag            = "manylinux_2_36_x86_64"
)

type PythonSourceProfileLock struct {
	Name, SourceID, IndexURL, IndexHost string
	DistributionHosts, OwnedProjects    []string
}

var PythonSourceProfiles = map[string]PythonSourceProfileLock{
	"pytorch:cpu":   {Name: "pytorch:cpu", SourceID: "pytorch-cpu", IndexURL: "https://download.pytorch.org/whl/cpu/", IndexHost: "download.pytorch.org", DistributionHosts: []string{"download.pytorch.org", "download-r2.pytorch.org"}, OwnedProjects: []string{"torch", "torchvision", "torchaudio"}},
	"pytorch:cu126": {Name: "pytorch:cu126", SourceID: "pytorch-cu126", IndexURL: "https://download.pytorch.org/whl/cu126/", IndexHost: "download.pytorch.org", DistributionHosts: []string{"download.pytorch.org", "download-r2.pytorch.org"}, OwnedProjects: []string{"torch", "torchvision", "torchaudio"}},
	"pytorch:cu130": {Name: "pytorch:cu130", SourceID: "pytorch-cu130", IndexURL: "https://download.pytorch.org/whl/cu130/", IndexHost: "download.pytorch.org", DistributionHosts: []string{"download.pytorch.org", "download-r2.pytorch.org"}, OwnedProjects: []string{"torch", "torchvision", "torchaudio"}},
	"pytorch:cu132": {Name: "pytorch:cu132", SourceID: "pytorch-cu132", IndexURL: "https://download.pytorch.org/whl/cu132/", IndexHost: "download.pytorch.org", DistributionHosts: []string{"download.pytorch.org", "download-r2.pytorch.org"}, OwnedProjects: []string{"torch", "torchvision", "torchaudio"}},
}

type GVisorBundleMemberLock struct {
	Path   string
	Size   int64
	SHA512 string
}

var GVisorRuntimeBundleMembers = []GVisorBundleMemberLock{
	{Path: "containerd-shim-runsc-v1", Size: 43502412, SHA512: "d0aa0cecaf048b1d42bc530e15a977f937d5e3f92996bc77c89817b899000ca5658e83f71a9f7adf91cad58961133549ef41239493f34c38c2572612d358826a"},
	{Path: "gvisor-bin/checkpointgofer", Size: 69039544, SHA512: "9c9faca22def369d1b009bf0ba1fd7cb86dad4cb0c3fc334f06d5fca07e7feee8c9c02925242d412345d934ce069fb0a9635000727cb4d49a97545686b8d1ea4"},
	{Path: "gvisor-bin/gvisor-sentry-prewarmer", Size: 1416, SHA512: "f0c131766303ca4733a4e42bd171d8ddf42a0a0087564605b3207b0f4c148d9ff355bad25e27d388c7c9cf06265160b3a02047ec195c035d9e8f428d8f608ce6"},
	{Path: "gvisor-bin/gvisor_sentry", Size: 51831363, SHA512: "97e71e1b575aa03a21ad3b816756b2a039f692a678d43382306838f94766f6cdb52a9515b211a557aa460fd64eb31edb9fdfb2702b80219994e6836b452c921e"},
	{Path: "gvisor-bin/runsc-metric-server", Size: 52895599, SHA512: "4a9cad01e92b3df8db5c4864494eb7bcc24a73af7491b764191b4f7964609f25e232681dc9a62f2d31b9d6d52a819276dd2b98b60847c326f2b781dc0199eb15"},
	{Path: "runsc", Size: 109388472, SHA512: "e3d0748b4f24f6472e0cb83b7728bd31b8cf4dbdd212f01bdc3f2c0fecaf6aea6449b3fcc2f1e90bd15f4603fa96bbe8a4a38bb8491603703557a1d84c7374d5"},
}
